version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - edge-vision-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - edge-vision-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9002:9002" # For websockets, if needed later
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config # Mount local config directory
    environment:
      - TZ=Asia/Kolkata
    networks:
      - edge-vision-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000" # Frontend
      - "8000:8000" # Backend
    environment:
      MONGO_URI: "mongodb://mongodb:27017/"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MQTT_BROKER_HOST: "mosquitto"
      MQTT_BROKER_PORT: "1883"
      TZ: Asia/Kolkata
    depends_on:
      - mongodb
      - minio
      - mosquitto
    volumes:
      - .:/app # Mount the entire project directory
    networks:
      - edge-vision-network

volumes:
  mongodb_data:
  minio_data:
  mosquitto_data:
  mosquitto_log:

networks:
  edge-vision-network:
    driver: bridge